## Interkulturelle Vergleichsanalyse mit der World Values Survey (WVS)

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

ModuleNotFoundError: No module named 'matplotlib'

In [9]:
# Daten einlesen
df = pd.read_csv("../data/WVS_Cross-National_Wave_7_csv_v6_0.csv", sep = ",")

/var/folders/v6/9c6hcq397n90s3n8znn3v7vh0000gn/T/ipykernel_22527/1619012253.py:2: DtypeWarning: Columns (0: X002_02B, 1: V002A_01, 2: V001A_01, 3: Partyname, 4: Partyabb, 5: CPARTY, 6: CPARTYABB) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/WVS_Cross-National_Wave_7_csv_v6_0.csv", sep = ",")

In [10]:
df.head()

,version,doi,A_WAVE,A_YEAR,A_STUDY,B_COUNTRY,B_COUNTRY_ALPHA,C_COW_NUM,C_COW_ALPHA,D_INTERVIEW,...,WVS_Polmistrust_PartyVoter,WVS_LR_MedianVoter,WVS_LibCon_MedianVoter,v2psbars,v2psorgs,v2psprbrch,v2psprlnks,v2psplats,v2xnp_client,v2xps_party
0,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2018,2,20,AND,232,AND,20070001,...,62.434211,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
1,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2018,2,20,AND,232,AND,20070002,...,62.434211,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
2,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2018,2,20,AND,232,AND,20070003,...,62.434211,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
3,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2018,2,20,AND,232,AND,20070004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2018,2,20,AND,232,AND,20070005,...,66.964286,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0

### Auswahl von Ländern und Merkmalen
USA: 840, Phillipinen: 608, Mexico: 484, Serbien: 688, Indien: 356

In [11]:
laender = [484, 356, 840, 608, 688]
df_country = df[df["B_COUNTRY"].isin(laender)]
df_country.head()

,version,doi,A_WAVE,A_YEAR,A_STUDY,B_COUNTRY,B_COUNTRY_ALPHA,C_COW_NUM,C_COW_ALPHA,D_INTERVIEW,...,WVS_Polmistrust_PartyVoter,WVS_LR_MedianVoter,WVS_LibCon_MedianVoter,v2psbars,v2psorgs,v2psprbrch,v2psprlnks,v2psplats,v2xnp_client,v2xps_party
37317,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2023,2,356,IND,750,IND,356070001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37318,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2023,2,356,IND,750,IND,356070002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37319,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2023,2,356,IND,750,IND,356070003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37320,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2023,2,356,IND,750,IND,356070004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37321,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2023,2,356,IND,750,IND,356070005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_country["B_COUNTRY_ALPHA"].value_counts()

B_COUNTRY_ALPHA
USA    2596
MEX    1741
IND    1692
PHL    1200
SRB    1046
Name: count, dtype: int64

In [21]:
# Fragen:
# Q250.- Importance of democracy
# Q251.- How democratically is this country being governed today
# Q235.- Political system: Having a strong leader who does not have to bother with parliament and elections

fragen = ["Q250", "Q251", "Q235"]

labels = {
    "Q250": "Wichtigkeit Demokratie",
    "Q251": "Wie demokratisch regiert",
    "Q235": "Starker Führer (Kein Parlament)"
}

# Mittelwerte pro Land
means = df_merkm.groupby("B_COUNTRY_ALPHA")[fragen].mean()

# N pro Land
n_per_country = df_merkm.groupby("B_COUNTRY_ALPHA")[fragen[0]].count().rename("N")

# Tabelle zusammenführen
means.columns = [labels[q] for q in means.columns]
table = n_per_country.to_frame().join(means).round(2)

print(table.to_string())

                    N  Wichtigkeit Demokratie  Wie demokratisch regiert  Starker Führer (Kein Parlament)
B_COUNTRY_ALPHA
IND              1692                    8.00                      6.35                             1.73
MEX              1741                    8.25                      5.16                             2.04
PHL              1200                    7.48                      6.92                             2.09
SRB              1046                    7.22                      4.92                             1.86
USA              2596                    8.15                      5.88                             2.82

In [22]:
latex = table.to_latex(
    caption="Mittelwerte ausgewählter WVS-Wave-7-Variablen nach Land ($N$ pro Land)",
    label="tab:wvs_means",
    column_format="l r " + "r " * len(fragen),
    escape=False,
    float_format="%.2f"
)
print(latex)

\begin{table}
\caption{Mittelwerte ausgewählter WVS-Wave-7-Variablen nach Land ($N$ pro Land)}
\label{tab:wvs_means}
\begin{tabular}{l r r r r}
\toprule
 & N & Wichtigkeit Demokratie & Wie demokratisch regiert & Starker Führer (Kein Parlament) \\
B_COUNTRY_ALPHA &  &  &  &  \\
\midrule
IND & 1692 & 8.00 & 6.35 & 1.73 \\
MEX & 1741 & 8.25 & 5.16 & 2.04 \\
PHL & 1200 & 7.48 & 6.92 & 2.09 \\
SRB & 1046 & 7.22 & 4.92 & 1.86 \\
USA & 2596 & 8.15 & 5.88 & 2.82 \\
\bottomrule
\end{tabular}
\end{table}

In [18]:
means = df_merkm.groupby("B_COUNTRY_ALPHA")[fragen].mean()
means

                     Q250      Q251      Q235
B_COUNTRY_ALPHA
IND              8.002364  6.349291  1.728723
MEX              8.251580  5.155658  2.039632
PHL              7.476667  6.923333  2.090833
SRB              7.218929  4.921606  1.863289
USA              8.149461  5.882512  2.815485

In [15]:
means.plot(kind="bar", figsize=(10, 5), rot=0)
plt.title("WVS Wave 7 – Ländervergleich")
plt.ylabel("Mittelwert")
plt.legend(["Q250: Wichtigkeit Demokratie", "Q251: Demokrat. Qualität", "Q235: Demokratie als Ziel"])
plt.tight_layout()
plt.show()

NameError: name 'means' is not defined

In [9]:
plt.figure(figsize=(8, 5))
sns.heatmap(means, annot=True, fmt=".2f", cmap="YlOrRd")
plt.title("WVS Wave 7 – Mittelwerte nach Land")
plt.tight_layout()
plt.show()

KeyError: 'Q5'

In [14]:
frage = "Q250"

# Häufigkeitstabelle
tabelle = df_merkm.groupby("B_COUNTRY")[frage].value_counts().unstack(fill_value=0)
print(tabelle)

Q5           -2  -1     1    2    3    4
B_COUNTRY
Deutschland  26  11   638  622  123  108
Äthiopien     0   0  1115  111    3    1

In [15]:
antworten = {
    1: "Very important",
    2: "Rather important",
    3: "Not very important",
    4: "Not at all important",
    -1: "Don´t know",
    -2: "No answer"
}

df_merkm[frage] = df_merkm[frage].map(antworten)

tabelle = df_merkm.groupby("B_COUNTRY")[frage].value_counts().unstack(fill_value=0)

# Prozente
tabelle_pct = tabelle.div(tabelle.sum(axis=1), axis=0).mul(100).round(1)

# Beides zusammen: n und %
tabelle_combined = tabelle.astype(str) + " (" + tabelle_pct.astype(str) + "%)"

print(tabelle_combined.T)

B_COUNTRY             Deutschland     Äthiopien
Q5
Don´t know              11 (0.7%)      0 (0.0%)
No answer               26 (1.7%)      0 (0.0%)
Not at all important   108 (7.1%)      1 (0.1%)
Not very important     123 (8.0%)      3 (0.2%)
Rather important      622 (40.7%)    111 (9.0%)
Very important        638 (41.8%)  1115 (90.7%)