## Interkulturelle Vergleichsanalyse mit der World Values Survey (WVS)

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
#import seaborn as sns

In [12]:
# Daten einlesen
df = pd.read_csv("../data/WVS_Cross-National_Wave_7_csv_v6_0.csv", sep = ",")

/var/folders/v6/9c6hcq397n90s3n8znn3v7vh0000gn/T/ipykernel_24471/1619012253.py:2: DtypeWarning: Columns (0: X002_02B, 1: V002A_01, 2: V001A_01, 3: Partyname, 4: Partyabb, 5: CPARTY, 6: CPARTYABB) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/WVS_Cross-National_Wave_7_csv_v6_0.csv", sep = ",")

In [21]:
df.head()

,version,doi,A_WAVE,A_YEAR,A_STUDY,B_COUNTRY,B_COUNTRY_ALPHA,C_COW_NUM,C_COW_ALPHA,D_INTERVIEW,...,WVS_Polmistrust_PartyVoter,WVS_LR_MedianVoter,WVS_LibCon_MedianVoter,v2psbars,v2psorgs,v2psprbrch,v2psprlnks,v2psplats,v2xnp_client,v2xps_party
0,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2018,2,20,AND,232,AND,20070001,...,62.434211,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
1,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2018,2,20,AND,232,AND,20070002,...,62.434211,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
2,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2018,2,20,AND,232,AND,20070003,...,62.434211,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0
3,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2018,2,20,AND,232,AND,20070004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2018,2,20,AND,232,AND,20070005,...,66.964286,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0,-999.0

## Auswahl von Ländern und Merkmalen
- USA: 840
- Phillipinen: 608
- Mexico: 484
- Serbien: 688
- Indien: 356

In [22]:
laender = [484, 356, 840, 608, 688]
df_country = df[df["B_COUNTRY"].isin(laender)]
df_country.head()

,version,doi,A_WAVE,A_YEAR,A_STUDY,B_COUNTRY,B_COUNTRY_ALPHA,C_COW_NUM,C_COW_ALPHA,D_INTERVIEW,...,WVS_Polmistrust_PartyVoter,WVS_LR_MedianVoter,WVS_LibCon_MedianVoter,v2psbars,v2psorgs,v2psprbrch,v2psprlnks,v2psplats,v2xnp_client,v2xps_party
37317,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2023,2,356,IND,750,IND,356070001,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37318,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2023,2,356,IND,750,IND,356070002,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37319,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2023,2,356,IND,750,IND,356070003,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37320,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2023,2,356,IND,750,IND,356070004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37321,6-0-0 (2024-04-30),doi.org/10.14281/18241.24,7,2023,2,356,IND,750,IND,356070005,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
df_country["B_COUNTRY_ALPHA"].value_counts()

B_COUNTRY_ALPHA
USA    2596
MEX    1741
IND    1692
PHL    1200
SRB    1046
Name: count, dtype: int64

## Merkmale zu Indikatoren zusammenfassen

In [ ]:
fragen = ['Q250', 'Q251', 'Q222', 'Q224', 'Q235', 'Q236', 'Q240', 'Q45', 'Q216', 'Q217', 'Q212', 'Q218']

# Nur relevante Spalten + Ländervariable behalten
df_merkm = df_country[["B_COUNTRY_ALPHA"] + fragen].copy()

df_merkm[fragen] = df_merkm[fragen].replace({-1: pd.NA, -2: pd.NA})
df_merkm = df_merkm.dropna(subset=fragen)

In [ ]:
# ── Indikator 1: Demokratische Werte & Institutionenvertrauen ──
df['idx_demokratie'] = df[['Q250', 'Q251', 'Q222', 'Q224']].mean(axis=1)

# ── Indikator 2: Autoritäre Disposition ──
# Q235, Q236, Q240 ggf. umpolen – hoher Wert = autoritärer
df['idx_autoritaer'] = df[['Q235', 'Q236', 'Q240', 'Q45']].mean(axis=1)

# ── Indikator 3: Medienvertrauen ──
df['idx_medien'] = df[['Q216', 'Q217', 'Q212', 'Q218']].mean(axis=1)

In [33]:
labels = {
    "idx_demokratie": "Demokratie",
    "idx_autoritaer": "Führungspräferenz",
    "idx_medien": "Medienverständnis"
}

# Mittelwerte pro Land
means = df_merkm.groupby("B_COUNTRY_ALPHA")[fragen].mean()

# N pro Land
n_per_country = df_merkm.groupby("B_COUNTRY_ALPHA")[fragen[0]].count().rename("N")

# Tabelle zusammenführen
means.columns = [labels[q] for q in means.columns]
table = n_per_country.to_frame().join(means).round(2)

print(table.to_string())

                    N Wichtigkeit Demokratie Wie demokratisch regiert Starker Führer (Kein Parlament)
B_COUNTRY_ALPHA
IND              1474               8.464043                 6.881275                        2.031208
MEX              1674               8.299881                 5.251493                        2.126643
PHL              1199               7.474562                 6.920767                        2.093411
SRB               900                    7.5                 5.206667                        2.365556
USA              2501               8.335866                  6.05118                        2.922431

In [35]:
means = df_merkm.groupby("B_COUNTRY_ALPHA")[fragen].mean()
means

                     Q250      Q251      Q235
B_COUNTRY_ALPHA
IND              8.464043  6.881275  2.031208
MEX              8.299881  5.251493  2.126643
PHL              7.474562  6.920767  2.093411
SRB                   7.5  5.206667  2.365556
USA              8.335866   6.05118  2.922431

In [23]:
means.plot(kind="bar", figsize=(10, 5), rot=0)
plt.title("WVS Wave 7 – Ländervergleich")
plt.ylabel("Mittelwert")
plt.legend(["Q250: Wichtigkeit Demokratie", "Q251: Demokrat. Qualität", "Q235: Demokratie als Ziel"])
plt.tight_layout()
plt.show()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [9]:
plt.figure(figsize=(8, 5))
sns.heatmap(means, annot=True, fmt=".2f", cmap="YlOrRd")
plt.title("WVS Wave 7 – Mittelwerte nach Land")
plt.tight_layout()
plt.show()

KeyError: 'Q5'

In [37]:
frage = "Q250"

# Häufigkeitstabelle
tabelle = df_merkm.groupby("B_COUNTRY_ALPHA")[frage].value_counts().unstack(fill_value=0)
print(tabelle)

Q250             1   2   3   4    5    6    7    8    9     10
B_COUNTRY_ALPHA
IND              29  33  24  28   45   80  105  169  205   756
MEX              39  12  23  32  111   99  155  227  176   800
PHL              47  27  28  37  143  102  113  176  157   369
SRB              18  13  20  26  122   62  111  187  123   218
USA              28  17  24  47  300  116  146  322  278  1223

In [38]:
# Antworten für Q250 und Q251
antworten_10 = {
    1: "Not at all democratic",
    2: "2", 3: "3", 4: "4", 5: "5",
    6: "6", 7: "7", 8: "8", 9: "9",
    10: "Completely democratic",
    -1: "Don´t know",
    -2: "No answer"
}

# Antworten für Q235
antworten_5 = {
    1: "Very good",
    2: "Fairly good",
    3: "Fairly bad",
    4: "Very bad",
    -1: "Don´t know",
    -2: "No answer"
}

# -1 und -2 als NA setzen und Zeilen droppen
df_merkm[["Q250", "Q251", "Q235"]] = df_merkm[["Q250", "Q251", "Q235"]].replace({-1: pd.NA, -2: pd.NA})
df_merkm = df_merkm.dropna(subset=["Q250", "Q251", "Q235"])

# Mapping anwenden
df_merkm["Q250_label"] = df_merkm["Q250"].map(antworten_10)
df_merkm["Q251_label"] = df_merkm["Q251"].map(antworten_10)
df_merkm["Q235_label"] = df_merkm["Q235"].map(antworten_5)

In [39]:
# Aggregierte Spalten: stimme zu / stimme nicht zu
# Q250 + Q251: Skala 1–10 → 1–5 = nicht zustimmend, 6–10 = zustimmend
df_merkm["Q250_agree"] = df_merkm["Q250"].apply(lambda x: "Agree" if x >= 6 else "Disagree")
df_merkm["Q251_agree"] = df_merkm["Q251"].apply(lambda x: "Agree" if x >= 6 else "Disagree")

# Q235: Skala 1–4 → 1–2 = zustimmend (good), 3–4 = nicht zustimmend (bad)
df_merkm["Q235_agree"] = df_merkm["Q235"].apply(lambda x: "Agree" if x <= 2 else "Disagree")

In [40]:
df_merkm.head()

,B_COUNTRY_ALPHA,Q250,Q251,Q235,Q250_label,Q251_label,Q235_label,Q250_agree,Q251_agree,Q235_agree
37317,IND,10,8,1,Completely democratic,8,Very good,Agree,Agree,Agree
37318,IND,10,7,1,Completely democratic,7,Very good,Agree,Agree,Agree
37319,IND,10,10,3,Completely democratic,Completely democratic,Fairly bad,Agree,Agree,Disagree
37320,IND,10,6,1,Completely democratic,6,Very good,Agree,Agree,Agree
37321,IND,10,7,1,Completely democratic,7,Very good,Agree,Agree,Agree

In [41]:
tabelle = df_merkm.groupby("B_COUNTRY_ALPHA")[frage].value_counts().unstack(fill_value=0)

# Prozente
tabelle_pct = tabelle.div(tabelle.sum(axis=1), axis=0).mul(100).round(1)

# Beides zusammen: n und %
tabelle_combined = tabelle.astype(str) + " (" + tabelle_pct.astype(str) + "%)"

print(tabelle_combined.T)

B_COUNTRY_ALPHA          IND          MEX          PHL          SRB  \
Q250
1                  29 (2.0%)    39 (2.3%)    47 (3.9%)    18 (2.0%)
2                  33 (2.2%)    12 (0.7%)    27 (2.3%)    13 (1.4%)
3                  24 (1.6%)    23 (1.4%)    28 (2.3%)    20 (2.2%)
4                  28 (1.9%)    32 (1.9%)    37 (3.1%)    26 (2.9%)
5                  45 (3.1%)   111 (6.6%)  143 (11.9%)  122 (13.6%)
6                  80 (5.4%)    99 (5.9%)   102 (8.5%)    62 (6.9%)
7                 105 (7.1%)   155 (9.3%)   113 (9.4%)  111 (12.3%)
8                169 (11.5%)  227 (13.6%)  176 (14.7%)  187 (20.8%)
9                205 (13.9%)  176 (10.5%)  157 (13.1%)  123 (13.7%)
10               756 (51.3%)  800 (47.8%)  369 (30.8%)  218 (24.2%)

B_COUNTRY_ALPHA           USA
Q250
1                   28 (1.1%)
2                   17 (0.7%)
3                   24 (1.0%)
4                   47 (1.9%)
5                 300 (12.0%)
6                  116 (4.6%)
7                  146 (5.8%)
8                 322 (12.9%)
9                 278 (11.1%)
10               1223 (48.9%)

In [42]:
for frage in ["Q250_agree", "Q251_agree", "Q235_agree"]:

    tabelle = df_merkm.groupby("B_COUNTRY_ALPHA")[frage].value_counts().unstack(fill_value=0)
    tabelle_pct = tabelle.div(tabelle.sum(axis=1), axis=0).mul(100).round(1)

    # N und % getrennt
    n_table = tabelle
    pct_table = tabelle_pct

    # Mittelwert über alle Länder
    n_table.loc["Total"] = n_table.sum()
    pct_table.loc["Total"] = pct_table.mean().round(1)

    # MultiIndex: n und % nebeneinander
    n_table.columns = pd.MultiIndex.from_product([n_table.columns, ["n"]])
    pct_table.columns = pd.MultiIndex.from_product([pct_table.columns, ["%"]])

    result = pd.concat([n_table, pct_table], axis=1).sort_index(axis=1)

    latex = result.to_latex(
        caption=f"Häufigkeiten und Anteile: {frage}",
        label=f"tab:{frage}",
        column_format="l" + "rr" * len(tabelle.columns),
        multicolumn=True,
        multicolumn_format="c",
        float_format="%.1f"
    )
    print(latex)

\begin{table}
\caption{Häufigkeiten und Anteile: Q250_agree}
\label{tab:Q250_agree}
\begin{tabular}{lrrrr}
\toprule
Q250_agree & \multicolumn{2}{c}{Agree} & \multicolumn{2}{c}{Disagree} \\
 & % & n & % & n \\
B_COUNTRY_ALPHA &  &  &  &  \\
\midrule
IND & 89.2 & 1315 & 10.8 & 159 \\
MEX & 87.0 & 1457 & 13.0 & 217 \\
PHL & 76.5 & 917 & 23.5 & 282 \\
SRB & 77.9 & 701 & 22.1 & 199 \\
USA & 83.4 & 2085 & 16.6 & 416 \\
Total & 82.8 & 6475 & 17.2 & 1273 \\
\bottomrule
\end{tabular}
\end{table}

\begin{table}
\caption{Häufigkeiten und Anteile: Q251_agree}
\label{tab:Q251_agree}
\begin{tabular}{lrrrr}
\toprule
Q251_agree & \multicolumn{2}{c}{Agree} & \multicolumn{2}{c}{Disagree} \\
 & % & n & % & n \\
B_COUNTRY_ALPHA &  &  &  &  \\
\midrule
IND & 76.6 & 1129 & 23.4 & 345 \\
MEX & 47.1 & 789 & 52.9 & 885 \\
PHL & 71.1 & 853 & 28.9 & 346 \\
SRB & 44.2 & 398 & 55.8 & 502 \\
USA & 60.1 & 1504 & 39.9 & 997 \\
Total & 59.8 & 4673 & 40.2 & 3075 \\
\bottomrule
\end{tabular}
\end{table}

\begin{table}
\caption{Häufigkeiten und Anteile: Q235_agree}
\label{tab:Q235_agree}
\begin{tabular}{lrrrr}
\toprule
Q235_agree & \multicolumn{2}{c}{Agree} & \multicolumn{2}{c}{Disagree} \\
 & % & n & % & n \\
B_COUNTRY_ALPHA &  &  &  &  \\
\midrule
IND & 69.1 & 1019 & 30.9 & 455 \\
MEX & 71.7 & 1200 & 28.3 & 474 \\
PHL & 74.8 & 897 & 25.2 & 302 \\
SRB & 50.6 & 455 & 49.4 & 445 \\
USA & 34.9 & 873 & 65.1 & 1628 \\
Total & 60.2 & 4444 & 39.8 & 3304 \\
\bottomrule
\end{tabular}
\end{table}

In [45]:
import plotly.express as px

fragen_config = {
    "Q250_agree": "Q250 – Importance of Democracy",
    "Q251_agree": "Q251 – Democratically Governed Today",
    "Q235_agree": "Q235 – Strong Leader (no Parliament)"
}

for frage, titel in fragen_config.items():

    tabelle = df_merkm.groupby("B_COUNTRY_ALPHA")[frage].value_counts(normalize=True).mul(100).round(1).reset_index()
    tabelle.columns = ["Land", "Antwort", "Prozent"]

    fig = px.bar(
        tabelle,
        x="Land",
        y="Prozent",
        color="Antwort",
        barmode="stack",
        title=titel,
        text="Prozent",
        color_discrete_map={"Agree": "#2E86AB", "Disagree": "#E84855"},
        labels={"Prozent": "Anteil (%)", "Land": "Land", "Antwort": ""}
    )

    fig.update_traces(texttemplate="%{text}%", textposition="inside")
    fig.update_layout(
        plot_bgcolor="white",
        yaxis=dict(range=[0, 100], ticksuffix="%"),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        font=dict(family="Arial", size=13),
        title_font_size=15
    )

    fig.show()

ModuleNotFoundError: No module named 'plotly'

In [46]:
agree_tabelle = pd.DataFrame()
fragen_config = {
    "Q250_agree": "Q250 – Importance of Democracy",
    "Q251_agree": "Q251 – Democratically Governed Today",
    "Q235_agree": "Q235 – Strong Leader (no Parliament)"
}
for frage, titel in fragen_config.items():
    pct = (
        df_merkm.groupby("B_COUNTRY_ALPHA")[frage]
        .value_counts(normalize=True)
        .mul(100)
        .round(1)
        .unstack(fill_value=0)
        ["Agree"]
        .rename(titel)
    )
    agree_tabelle = pd.concat([agree_tabelle, pct], axis=1)

agree_tabelle.loc["Ø Gesamt"] = agree_tabelle.mean().round(1)

print(agree_tabelle.to_string())

          Q250 – Importance of Democracy  Q251 – Democratically Governed Today  Q235 – Strong Leader (no Parliament)
IND                                 89.2                                  76.6                                  69.1
MEX                                 87.0                                  47.1                                  71.7
PHL                                 76.5                                  71.1                                  74.8
SRB                                 77.9                                  44.2                                  50.6
USA                                 83.4                                  60.1                                  34.9
Ø Gesamt                            82.8                                  59.8                                  60.2

In [47]:
latex = agree_tabelle.to_latex(
    caption="Anteil Agree-Antworten nach Land (in \%)",
    label="tab:agree_gesamt",
    column_format="l" + "r" * len(fragen_config),
    float_format="%.1f",
    escape=False
)
print(latex)

\begin{table}
\caption{Anteil Agree-Antworten nach Land (in \%)}
\label{tab:agree_gesamt}
\begin{tabular}{lrrr}
\toprule
 & Q250 – Importance of Democracy & Q251 – Democratically Governed Today & Q235 – Strong Leader (no Parliament) \\
\midrule
IND & 89.2 & 76.6 & 69.1 \\
MEX & 87.0 & 47.1 & 71.7 \\
PHL & 76.5 & 71.1 & 74.8 \\
SRB & 77.9 & 44.2 & 50.6 \\
USA & 83.4 & 60.1 & 34.9 \\
Ø Gesamt & 82.8 & 59.8 & 60.2 \\
\bottomrule
\end{tabular}
\end{table}

<>:2: SyntaxWarning: invalid escape sequence '\%'
<>:2: SyntaxWarning: invalid escape sequence '\%'
/var/folders/v6/9c6hcq397n90s3n8znn3v7vh0000gn/T/ipykernel_24471/2335143965.py:2: SyntaxWarning: invalid escape sequence '\%'
  caption="Anteil Agree-Antworten nach Land (in \%)",